language: go
install:
    - go get -d google.golang.org/appengine
    - wget https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.40.zip -O /tmp/go_appengine.zip
    - unzip -qd /tmp /tmp/go_appengine.zip
script:
    - export PATH=/tmp/go_appengine:$PATH
    - go test -v
